### ISSUE TITLE
Rasha Ali: Week 1,Encapsulation

### ISSUE THREAD

**Issue by Rashaali84** [HackYourFutureBelgium/class-8#240]
### Prep Work

- [ ] one prep topic
- [ ] the next prep topic
- [ ] ...

### Name of Project:

- [repository](github.com/user-name/repo-name)
- [live demo](https://user-name.github.io/repo-name)
- [ ]  [step 1](link to branch for version 1)
- [ ]  [step 2](link to branch for version 2)
- [ ]  [step 3](link to branch for version 3)
- [ ]  ...

### Exercises:

- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] ...

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by bramdevries** [comment]
**numbery-organizer**

Nice job on this exercise, I found it quite challenging myself.

There's a lot of duplicate code in there to check if the `param` is a `string` or a `number`. One way to reduce this is by having specific functions for checking this, eg:

```js
function assertNumber (value) {
 return typeof param === 'number' || Number(param) || param === '';
}

function assertString (value) {
  return typeof value === 'string';
}
```

This allows you to re-use them in your object:

```js
if (!assertString(param))
      return false;
else {
	if (assertNumber(param))
		this.numberyStrings.push(param);
	else
        this.NaNyStrings.push(param);
		return true;
}
```

Another improvement you can make for readability is to use early return statements. For example the `addString` method could become:

```js
if (!assertString(param)) {
  return false;
}

if (assertNumber(param)) {
  this.numberyStrings.push(param);
  
  return true;
}

this.NaNyStrings.push(param);

return true;
```

In your `sumOf*` methods you are checking the length of the numbers to return `0` if they are empty. You can get to a similar result by using the 2nd argument of [`reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce). This will set the initial value you receive.

```js
this.NaNyStrings.reduce(function (acc, value) {
	return acc + value;
}, 0);
```

Finally, in those `sumOf*` methods you can also re-use the other methods, this means you can simplify them greatly by using the `*AsNumbers` methods because they already handle getting the numeric value.

```js
sumOfNumbery: function () {
  return this.numberyAsNumbers().reduce((total, value) => {
    return total + value;
  }, 0);
},
sumOfNaNy: function () {
  return this.NaNyAsNumbers().reduce((total, value) => {
    return total + value;
  }, 0);
},
```


**getters-and-setters**

A very minor thing but try to keep getters and setters lowercase. 

**Todo list project**

I really liked that your `todoList` object contained very clear names such as `changeTodo`, `deleteTodo`, etc. You could simplify them even further to `change` and `delete` since the `Todo` is implied by the `TodoList` object.

A small suggestion to get the amount of completed todos is to use a combination of [`filter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) and `length`:

```js
var completedTodos = this.todos.filter(function (todo) {
  return todo.completed === true;
}).length;
```

---

Very nice job @Rashaali84! The feedback I've written might be a bit overwhelming but it's really only minor improvements.

**Comment by Rashaali84** [comment]
Thank you so much for your detailed useful remarks Bram ! :+1:  that was really informative !! , will try to keep an eye on reducing code lines by using chaining methods , and code reusing in the future ..
